services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    restart: unless-stopped 
    ports:
      - "80:80"     # http
      - "81:81"     # http
      - "443:443"   # https
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - ngnx_pm_network

networks:
  ngnx_pm_network:
    external: true