services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    restart: unless-stopped
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    # healthcheck:
    #   test: ["CMD", "bash", "-c", ":> /dev/tcp/127.0.0.1/8945 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 90s
    volumes:
      - ./config:/config:rw
      - ./downloads:/downloads:rw
    networks:
      - ngnx_pm_network

networks:
  ngnx_pm_network:
    external: true