services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"     # http
      - "443:443"   # https
      - "8080:8080" # Traefik control center access
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./certs:/etc/traefik/certs:ro"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true