services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    # healthcheck:
      # test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      # interval: 30s
      # timeout: 10s
      # retries: 5
    networks:
      - ngnx_pm_network

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - ngnx_pm_network

networks:
  ngnx_pm_network:
    external: true